category: Security
questions:
    -
        question: 'Which line is correct to add a security.access_control line?'
        answers:
            - {value: "- { path: ^/admin, roles: ROLE_ADMIN }", correct: true}
            - {value: "- { path: ^/admin, acl: ROLE_ADMIN }",   correct: false}
            - {value: "- { url: ^/admin, roles: ROLE_ADMIN }",  correct: false}
            - {value: "- { url: ^/admin, acl: ROLE_ADMIN }",    correct: false}
    -
        question: 'After a login success, what is the parameter name to redirect on referer URL?'
        answers:
            - {value: security.firewalls.<name>.form_login.use_referer,         correct: true}
            - {value: security.firewalls.<name>.form_login.after_login_referer, correct: false}
            - {value: security.firewalls.<name>.form_login.referer,             correct: false}
            - {value: security.firewalls.<name>.form_login.success_referer,     correct: false}
